In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/Edward/Downloads/open_postcode_geo.csv/open_postcode_geo.csv")
data

         AB1 0AA  terminated  small  385386   801193  ...  AB  AB1  AB1 0 AB1.1  0AA
0        AB1 0AB  terminated  small  385177   801314  ...  AB  AB1  AB1 0   AB1  0AB
1        AB1 0AD  terminated  small  385053   801092  ...  AB  AB1  AB1 0   AB1  0AD
2        AB1 0AE  terminated  small  384600   799300  ...  AB  AB1  AB1 0   AB1  0AE
3        AB1 0AF  terminated  large  384460   800660  ...  AB  AB1  AB1 0   AB1  0AF
4        AB1 0AG  terminated  large  383890   800710  ...  AB  AB1  AB1 0   AB1  0AG
...          ...         ...    ...     ...      ...  ...  ..  ...    ...   ...  ...
2631530  ZE3 9JW        live  small  438975  1110038  ...  ZE  ZE3  ZE3 9   ZE3  9JW
2631531  ZE3 9JX        live  small  438872  1110219  ...  ZE  ZE3  ZE3 9   ZE3  9JX
2631532  ZE3 9JY        live  small  438498  1112029  ...  ZE  ZE3  ZE3 9   ZE3  9JY
2631533  ZE3 9JZ        live  small  438662  1112122  ...  ZE  ZE3  ZE3 9   ZE3  9JZ
2631534  ZE3 9XP  terminated  large  438854  1111535  ...  ZE  ZE3  ZE3 9   ZE3  9XP

[2631535 rows x 17 columns]

In [16]:
df = pd.read_csv("/Users/Edward/Downloads/hiddenckd_postcodes.csv")
df.columns = ['date', 'event_address', 'event_postcode', 'gp_postcode']
df

            date  ...        gp_postcode
0     23/10/2022  ...           SE17 3DW
1     23/10/2022  ...            SE4 2LA
2     23/10/2022  ...            SE4 2LA
3     23/10/2022  ...           SE26 5BJ
4     23/10/2022  ...  Prefer not to say
...          ...  ...                ...
1061  04/11/2023  ...  Prefer not to say
1062  04/11/2023  ...            E12 5JG
1063  04/11/2023  ...  Prefer not to say
1064  04/11/2023  ...  Prefer not to say
1065  04/11/2023  ...  Prefer not to say

[1066 rows x 4 columns]

In [17]:
coord = data[['AB1 0AA', '57.101474', '-2.242851']].copy()
coord.columns = ['gp_postcode', 'lat', 'long']

In [18]:
# Convert both to string (object) type
df['gp_postcode'] = df['gp_postcode'].astype(str)
coord['gp_postcode'] = coord['gp_postcode'].astype(str)

merged_df = df.join(coord.set_index('gp_postcode'), on='gp_postcode', how='left')
merged_df = merged_df.rename(columns={'lat':'gp_lat', 'long':'gp_long'})
coord = coord.rename(columns={'gp_postcode':'event_postcode'})
merged_df = merged_df.join(coord.set_index('event_postcode'), on='event_postcode', how='left')
merged_df = merged_df.rename(columns={'lat':'event_lat', 'long':'event_long'})
merged_df

            date  ... event_long
0     23/10/2022  ...   0.071376
1     23/10/2022  ...   0.071376
2     23/10/2022  ...   0.071376
3     23/10/2022  ...   0.071376
4     23/10/2022  ...   0.071376
...          ...  ...        ...
1061  04/11/2023  ...   0.023497
1062  04/11/2023  ...   0.023497
1063  04/11/2023  ...   0.023497
1064  04/11/2023  ...   0.023497
1065  04/11/2023  ...   0.023497

[1066 rows x 8 columns]

In [19]:
import numpy as np

# Radius of Earth in kilometers
R = 6371.0

merged_df['event_lat'] = pd.to_numeric(merged_df['event_lat'], errors='coerce')
merged_df['event_long'] = pd.to_numeric(merged_df['event_long'], errors='coerce')
merged_df['gp_lat'] = pd.to_numeric(merged_df['gp_lat'], errors='coerce')
merged_df['gp_long'] = pd.to_numeric(merged_df['gp_long'], errors='coerce')

# Convert degrees to radians
event_lat_rad = np.radians(merged_df['event_lat'])
event_long_rad = np.radians(merged_df['event_long'])
gp_lat_rad = np.radians(merged_df['gp_lat'])
gp_long_rad = np.radians(merged_df['gp_long'])

# Differences
delta_lat = gp_lat_rad - event_lat_rad
delta_long = gp_long_rad - event_long_rad

# Haversine formula
a = np.sin(delta_lat / 2)**2 + np.cos(event_lat_rad) * np.cos(gp_lat_rad) * np.sin(delta_long / 2)**2
c = 2 * np.arcsin(np.sqrt(a))

# Distance in kilometers
merged_df['distance_km'] = R * c

In [20]:
merged_df = merged_df.drop(columns=['gp_lat', 'gp_long', 'event_lat', 'event_long'])

In [22]:
merged_df.to_csv('/Users/Edward/Downloads/hiddenckd_travel_distances.csv', index=False)